name: Maven Test on Spring Boot

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: chekout
        uses: actions/checkout@v4

      - name: setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: setup maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.5.2'

      - name: cache dependency
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build & Unit Test
        run: mvn clean test
