CREATE TABLE IF NOT EXISTS users (
    id INTEGER AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL DEFAULT 'pw',
    role ENUM('ADMIN', 'USER') NOT NULL DEFAULT 'USER',
    PRIMARY KEY (id),
    UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER AUTO_INCREMENT NOT NULL,
    title VARCHAR(50) NOT NULL,
    status ENUM('AVAIlABLE', 'BORROWED') NOT NULL DEFAULT 'AVAIlABLE',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS borrow_records (
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id INTEGER,
    book_id INTEGER,
    borrowed_date DATETIME NOT NULL,
    returned_date DATETIME,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);
